spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/csceats_test
    username: postgres
    password: babanotakada
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.backend.entity